### ISSUE TITLE
cannot load LLaVA model onto GPU on Colab

### ISSUE THREAD

**Issue by DiTo97** [Reply-AGI-CoP/area42-swat-concept-graphs#1]
For more information, see [#1027](https://github.com/abetlen/llama-cpp-python/issues/1027) with @Fra-Tsuna.

**Comment by Fra-Tsuna** [comment]
@DiTo97 
I've just uploaded in b7f210d32081e1ab2d1fd10885d2effa785e0e3c the python notebook that we used for our tests.
According to ableten's answers there are some things to be changed in order to make it completely work on GPU.
We need to 

- change compilation flags and install with CUBLAS support rather than OpenBLAS
- use additional python libraries to enable CLIP offloading (not natively supported in llama.cpp)

I'll try to make these tests as soon as possible and I'll keep you updated

**Comment by DiTo97** [comment]
> @DiTo97 I've just uploaded in [b7f210d](https://github.com/Reply-AGI-CoP/area42-swat-concept-graphs/commit/b7f210d32081e1ab2d1fd10885d2effa785e0e3c) the python notebook that we used for our tests. According to abetlen's answers there are some things to be changed in order to make it completely work on GPU. We need to
> 
> * change compilation flags and install with CUBLAS support rather than OpenBLAS
> * use additional python libraries to enable CLIP offloading (not natively supported in llama.cpp)
> 
> I'll try to make these tests as soon as possible and I'll keep you updated

That looks good! Probably, I will create a contrib branch so we can start commiting code there, before modifying the main brack.

As for abetlen's second suggestion, it would likely gain us some time, but we have to think if it's worth the effort. I already have some pytorch code using CLIP, but we would have to implement those abstraction layers.

**Comment by DiTo97** [comment]
> I confirm that by installing with CUBLAS the model is loaded in GPU correctly `!CMAKE_ARGS="-DLLAMA_CUBLAS=ON" python -m pip install llama-cpp-python`
> 
> ![immagine](https://private-user-images.githubusercontent.com/68866971/291530044-7808bfdd-b0f9-471e-a293-d1593d1b0d3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODg4NjksIm5iZiI6MTcwMjk4ODU2OSwicGF0aCI6Ii82ODg2Njk3MS8yOTE1MzAwNDQtNzgwOGJmZGQtYjBmOS00NzFlLWEyOTMtZDE1OTNkMWIwZDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDEyMjI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4M2M2MjI0ZDNiZWU3MzEzYTZkYjU1ZjA0ZjlmZmU2ODdkYzhmYmMxNmY1NzdjZTA1MDVlY2Y2MGMwM2VjMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dwPTkOz3f0T81zPDc7pdoI6x-Kg5s7fHgS8Cs8nmO6w)
> 
> With just this change, the inference time become of ~15s of normal chat completion, and ~12s of chat completion with the enforced grammar. It's already quite fast, I'll try to make the other changes to make it faster.

12s looks fast enough, grammar helps.

From the usage charts, it seems the GPU is still very much underutilized from a single forward call, so another option to cut overall runtime would be using batch decoding. At the moment, the scene graph construction code loops through and processes each segmented object one by one.

**Comment by Fra-Tsuna** [comment]
> As for abetlen's second suggestion, it would likely gain us some time, but we have to think if it's worth the effort. I already have some pytorch code using CLIP, but we would have to implement those abstraction layers.

Yeah I think so, it seems non trivial to me do do such a procedure, especially for the abstraction layers. If you have already some code we might try it tho, maybe not as our may priority.

> From the usage charts, it seems the GPU is still very much underutilized from a single forward call, so another option to cut overall runtime would be using batch decoding. At the moment, the scene graph construction code loops through and processes each segmented object one by one.

Once we start modifying the scene graph construction code we could for sure implement the batch decoding
